name: Generate Examples

on: [push, pull_request, release]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build Cargo
        run: cargo clean && cargo build --verbose && cargo install --path language
      - name: Build Cargo - Examples
        run: cargo clean && cargo build --verbose
        working-directory: ./examples
      - name: Generate Coq files
        run: cargo hacspec -e v --dir ../coq/src/ "*" --vc-update
	working-directory: ./examples
      - name: Generate Easycrypt files
        run: cargo hacspec -e ec --dir ../easycrypt/ "*" --vc-update
	working-directory: ./examples
      - name: Generate Fstar files
        run: cargo hacspec -e fst --dir ../fstar/ "*" --vc-update
	working-directory: ./examples